### ISSUE TITLE
Roadmap: Typescript

### ISSUE THREAD

**Issue by crrice** [crrice/geofire-js#2]
I'd like to rewrite this repo in typescript for that juicy type safety and es6+ features.

- [ ] Add tsconfig file
- [ ] Rewrite geoFire.js
- [ ] Rewrite geoFireUtils.js
- [ ] Rewrite geoQuery.js (this is the hard one)
- [ ] Rewrite geoCallbackRegistration.js

Additionally, some other misc improvements?

- [ ] Export ES2015 module (per issue 123 in the original repo).
- [ ] Update dependencies so firebase 4+ is supported (npm issue, code is already compatible).
- [ ] Add support for rectangular queries (and maybe queries by user specified geohash prefix).

And maybe even some API breaking changes just because.

- [ ] Convert distance units to use the standard SI unit of METERS for the criteria radius.

**This is just a wishlist, and who knows which of these I will actually decide to implement. Nothing is certain.**

**Comment by crrice** [comment]
Alright, I guess this might be better placed as a project, not an issue. Closing it and moving.
